### ISSUE TITLE
Set upload file size limit

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-web#4]
It would be helpful to be able to configure that maximum size of a generator/solver that a user may upload. Right now, in the default configuration, the webserver already rejects such files when they are 15MB large.

**Comment by ImogenBits** [comment]
There are two parts to this, one is manually wanting to limit the file size of student uploads and the other that parts of the toolchain don't like very large http request bodies. The first has now been implemented in version 0.15.0.

The second is much weirder to deal with since I'm also not sure what those other parts really are. The problems we were running into until now were squarely my nginx container's fault though, I've increased its cap to 2GB. This means that in principle you can now set the manual limit to anything up to that, but large values might still not work due to external factors.

If a student wants to use a very large program the best way to work around this is to store the image (or large parts of it) in the docker hub and then only upload a thin wrapper to our webserver that builds off of that image.
